persistent-workspaces = ["Discord"]

[mode.main.binding]
    alt-5 = 'workspace Discord'
    alt-shift-5 = ['move-node-to-workspace Discord', 'workspace Discord']

[mode.service.binding]
    # Entries to insert into 'd' before the exit commands
    d = [
        'move-workspace-to-monitor --workspace Discord secondary "Built-in Retina Display" 2',
        'workspace Discord',
    ]
